---
- hosts: all
  become: yes
  vars:
    python_version: 3.4
    root_dir: /home/vagrant/myproject
    postgresql_databases:
      - name: todo
  roles:
  - { role: ANXS.postgresql }
  tasks:
  - name: Ensure Python is installed
    apt: name=python{{ python_version }} state=present
  - name: Ensure Python setuptools are installed
    apt: name=python3-setuptools state=latest
  - name: Ensure pip is installed
    easy_install: name=pip state=latest executable=easy_install3
  - name: Ensure devel libraries are installed
    apt: name={{ item }} state=latest
    with_items:
      - libpq-dev
      - libpython3-dev
  - name: Install Python Packages
    pip: requirements={{ root_dir }}/requirements.txt
